title: James Purdy
description: iOS Software Engineering
permalink: /:title/
baseurl: ""
url: http://swiftdeveloper.ninja
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: James Purdy
author-img: j-purdy.jpg
about-author: I am a Software Engineer who specializes in iOS development. Some of the enterprise iOS projects I’ve worked on include apps for OfferUp, NEC, Intel, Disney, Toyota, and Grab. I am currently an iOS Dev @ Smartsheet.
social-twitter: pixelcloudst
social-linkedin: jamespurdy
social-email: jameswpurdy@gmail.com

# Disqus
discus-identifier: swift-developer-ninja

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed

paginate: 15
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
